
name: nix:build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v3

    - name: Install Nix ❄
      uses: cachix/install-nix-action@v20
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

    - name: Link Cachix 🔌
      uses: cachix/cachix-action@v12
      with:
        name: cofree-coffee
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    
    - name: Deploy 🚀
      run: nix build
